# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu backup.tf — AWS Backup vault + plan
# Organization: AcmeBank
# Profile:      ADVANCED
# Generated:    2026-09-01T14:06:53.658419Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

resource "aws_backup_vault" "central" {
  name          = "central-vault"
  kms_key_arn   = aws_kms_key.accelerator.arn
  force_destroy = false

  tags = local.default_tags
}

# Cross-region copy destination (warm-standby DR). A regional outage must not
# take the recovery points with it, so the daily plan copies every recovery
# point here. Encrypted with a customer-managed key in the DR region
# (aws_kms_key.backup_dr, see kms.tf) — satisfies CKV_AWS_166 and keeps the
# recovery points under a CMK in the same sovereignty boundary as the vault.
resource "aws_backup_vault" "central_dr" {
  provider      = aws.backup_dr
  name          = "central-vault-dr"
  kms_key_arn   = aws_kms_key.backup_dr.arn
  force_destroy = false
  tags          = local.default_tags
}

resource "aws_backup_vault_lock_configuration" "central" {
  backup_vault_name   = aws_backup_vault.central.name
  changeable_for_days = 3
  max_retention_days  = 2555
  min_retention_days  = 365
}

resource "aws_iam_role" "backup" {
  name = "AWSBackupServiceRole"

  assume_role_policy = jsonencode({
    Version   = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "backup.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy_attachment" "backup_managed" {
  role       = aws_iam_role.backup.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"
}

resource "aws_iam_role_policy_attachment" "backup_restore_managed" {
  role       = aws_iam_role.backup.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores"
}

# Default daily backup plan
resource "aws_backup_plan" "daily" {
  name = "acmebank-daily"

  rule {
    rule_name         = "DailyAtMidnightUTC"
    target_vault_name = aws_backup_vault.central.name
    schedule          = "cron(0 5 ? * * *)"
    start_window      = 60
    completion_window = 180

    lifecycle {
      cold_storage_after = 30
      delete_after       = 2555
    }
    # Replicate every daily recovery point to the DR region (warm standby).
    copy_action {
      destination_vault_arn = aws_backup_vault.central_dr.arn
      lifecycle {
        cold_storage_after = 30
        delete_after       = 2555
      }
    }

    recovery_point_tags = local.default_tags
  }

  tags = local.default_tags
}

data "aws_caller_identity" "current" {}

resource "aws_backup_selection" "daily" {
  iam_role_arn = aws_iam_role.backup.arn
  name         = "daily-tagged"
  plan_id      = aws_backup_plan.daily.id

  selection_tag {
    type  = "STRINGEQUALS"
    key   = "Backup"
    value = "true"
  }
}

# Organization-wide backup policy
resource "aws_organizations_policy" "backup" {
  name        = "Org-Backup-Policy-Daily"
  description = "Org-wide daily backup of in-scope resources to the central vault."
  type        = "BACKUP_POLICY"

  content = jsonencode({
    plans = {
      "org-daily" = {
        regions = { "@@assign" = ["eu-central-1", "eu-west-3"] }
        rules = {
          DailyAtMidnight = {
            schedule_expression = { "@@assign" = "cron(0 5 ? * * *)" }
            start_backup_window_minutes = { "@@assign" = "60" }
            complete_backup_window_minutes = { "@@assign" = "180" }
            lifecycle = {
              delete_after_days       = { "@@assign" = "2555" }
              move_to_cold_storage_after_days = { "@@assign" = "30" }
            }
            target_backup_vault_name = { "@@assign" = aws_backup_vault.central.name }
            # Org-wide: each member account copies daily recovery points to its
            # own vault in eu-west-3 (warm-standby DR).
            copy_actions = {
              "arn:aws:backup:eu-west-3:$account:backup-vault:central-vault-dr" = {
                target_backup_vault_arn = { "@@assign" = "arn:aws:backup:eu-west-3:$account:backup-vault:central-vault-dr" }
                lifecycle = {
                  delete_after_days = { "@@assign" = "2555" }
                }
              }
            }
            recovery_point_tags = {
              ManagedBy = { tag_key = { "@@assign" = "ManagedBy" }, tag_value = { "@@assign" = "Merlin-Studio-v2" } }
            }
          }
        }
        selections = {
          tags = {
            "tagged-for-backup" = {
              iam_role_arn   = { "@@assign" = aws_iam_role.backup.arn }
              tag_key        = { "@@assign" = "Backup" }
              tag_value      = { "@@assign" = ["true"] }
            }
          }
        }
      }
    }
  })
}
