# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu providers.tf
# Organization: AcmeBank
# Profile:      ADVANCED
# Generated:    2026-09-01T14:06:53.658419Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

# Default provider: home region
provider "aws" {
  region = "eu-central-1"

  default_tags {
    tags = local.default_tags
  }
}

locals {
  default_tags = {
    ManagedBy    = "Merlin-Studio-v2"
    Organization = "AcmeBank"
    Profile      = "advanced"
    Environment  = "multi_env"
    CostCenter   = "PLATFORM"
    # Owner is REQUIRED by the org tag policy (tag-policies/standard-tagging.json).
    Owner        = "Platform-Team"
    Compliance   = "cis,pci_dss,gdpr,iso27001,eucs"
  }
}

provider "aws" {
  alias  = "backup_dr"
  region = "eu-west-3"
  default_tags {
    tags = local.default_tags
  }
}

provider "aws" {
  alias  = "appdev"
  region = "eu-central-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppDev:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appdev-eu-central-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "appprod"
  region = "eu-central-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppProd:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appprod-eu-central-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "appprod_eu_west_3"
  region = "eu-west-3"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppProd:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appprod-eu-west-3"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "appstaging"
  region = "eu-central-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_AppStaging:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-appstaging-eu-central-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "network"
  region = "eu-central-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Network:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-network-eu-central-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "network_eu_west_3"
  region = "eu-west-3"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Network:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-network-eu-west-3"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "pciworkload"
  region = "eu-central-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_PciWorkload:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-pciworkload-eu-central-1"
  }
  default_tags {
    tags = local.default_tags
  }
}
provider "aws" {
  alias  = "sharedservices"
  region = "eu-central-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_SharedServices:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-sharedservices-eu-central-1"
  }
  default_tags {
    tags = local.default_tags
  }
}

# Provider for log archive account (cross-account writes)
provider "aws" {
  alias  = "log_archive"
  region = "eu-central-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_LogArchive:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-log-archive"
  }
  default_tags {
    tags = local.default_tags
  }
}

# Log archive account, eu-west-3 — hosts the central-logs
# CMK replica so the replicated log bucket's objects are decryptable in DR.
provider "aws" {
  alias  = "log_archive_eu_west_3"
  region = "eu-west-3"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_LogArchive:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-log-archive-eu-west-3"
  }
  default_tags {
    tags = local.default_tags
  }
}

# Provider for audit / security tooling account
provider "aws" {
  alias  = "audit"
  region = "eu-central-1"
  assume_role {
    role_arn     = "arn:aws:iam::PLACEHOLDER_ACCOUNT_ID_Audit:role/OrganizationAccountAccessRole"
    session_name = "merlin-studio-audit"
  }
  default_tags {
    tags = local.default_tags
  }
}