# Generated by Merlin Studio (https://app.merlin-studio.cloud). Licensed under the Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

# -----------------------------------------------------------------------------
# Generated by Merlin Studio v2 (architex-v2) — OpenTofu s3_log_archive.tf — central log archive bucket
# Organization: AcmeBank
# Profile:      ADVANCED
# Generated:    2026-09-01T14:06:53.658419Z
# Wizard:       v1.0.0
# -----------------------------------------------------------------------------
# Scaffolding — not a finished artifact. Merlin renders this from your
# declared intent (profile, frameworks, accounts, topology). Adapt it to
# your environment: tighten CIDRs, refine policy bodies, add team tags,
# pin module versions, layer account-specific overrides. Re-run the wizard
# when *intent* shifts; keep day-to-day customisation in your IaC fork
# (regen overwrites this directory).
# Replace PLACEHOLDER_ tokens with real values from your AWS Organization
# before `tofu apply` / `cdk deploy` / LZA pipeline run — see PLACEHOLDERS.md.

locals {
  central_logs_bucket_prefix = "acmebank-central-logs"
  central_logs_bucket_name   = "${local.central_logs_bucket_prefix}-${random_id.bucket_suffix.hex}"
}

# Access logging on the central log archive itself would either route logs
# back into the same bucket (circular logging, makes the bucket grow
# faster than it can be archived) or require yet another archive bucket
# to be the target — which would itself need access logging, recursing.
# Instead the bucket is monitored via CloudTrail S3 data events (see
# cloudtrail.tf — s3_data_events is enabled under FedRAMP/HIPAA/PCI/NIST)
# and the SNS event notifications above. CKV_AWS_18 is suppressed for
# this reason; see SECURITY_SCORECARD.md "Suppressed Checks".
resource "aws_s3_bucket" "central_logs" {
  # checkov:skip=CKV_AWS_18: Access logging on a log archive is circular; CloudTrail S3 data events + SNS notifications cover this surface
  provider = aws.log_archive
  bucket   = local.central_logs_bucket_name

  force_destroy = false
  # Object Lock can only be enabled at bucket creation (AWS provider v4+); the
  # COMPLIANCE retention rule below cannot attach otherwise (InvalidBucketState).
  object_lock_enabled = true

  tags = merge(local.default_tags, {
    Name    = "central-logs"
    Purpose = "Org-wide log archive for CloudTrail, Config, VPC flow logs, ELB"
  })
}

resource "random_id" "bucket_suffix" {
  byte_length = 4
}

resource "aws_s3_bucket_versioning" "central_logs" {
  provider = aws.log_archive
  bucket   = aws_s3_bucket.central_logs.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "central_logs" {
  provider = aws.log_archive
  bucket   = aws_s3_bucket.central_logs.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.central_logs.arn
      sse_algorithm     = "aws:kms"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "central_logs" {
  provider                = aws.log_archive
  bucket                  = aws_s3_bucket.central_logs.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_lifecycle_configuration" "central_logs" {
  provider = aws.log_archive
  bucket   = aws_s3_bucket.central_logs.id

  # Dedicated unfiltered rule for failed-multipart cleanup (CKV_AWS_300).
  # Checkov flags the abort block when it sits in a filtered rule because the
  # filter could exclude some prefixes from the cleanup; a separate unfiltered
  # rule guarantees coverage for every key in the bucket.
  rule {
    id     = "abort-incomplete-multipart-uploads"
    status = "Enabled"
    filter {}
    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  rule {
    id     = "expire-old-logs"
    status = "Enabled"
    filter {
      prefix = ""
    }
    noncurrent_version_expiration {
      noncurrent_days = 90
    }
    expiration {
      days = 3650
    }
    transition {
      days          = 30
      storage_class = "STANDARD_IA"
    }
    transition {
      days          = 90
      storage_class = "GLACIER"
    }
  }
}

# Object Lock (WORM) — required by: pci_dss.
# COMPLIANCE mode: no principal (including root) can shorten or delete
# retained versions. NOTE: Object Lock can only be enabled at bucket creation;
# it cannot be retrofitted onto an existing bucket — regenerating for an
# already-deployed landing zone requires a new bucket + data migration.
resource "aws_s3_bucket_object_lock_configuration" "central_logs" {
  provider = aws.log_archive
  bucket   = aws_s3_bucket.central_logs.id

  rule {
    default_retention {
      mode = "COMPLIANCE"
      # Never below the strictest declared framework's central-log floor
      # (PCI-DSS 10.5.1 requires >= 365 days).
      days = 3650
    }
  }
}

# Bucket policy permitting CloudTrail + Config to write
resource "aws_s3_bucket_policy" "central_logs_cloudtrail" {
  provider = aws.log_archive
  bucket   = aws_s3_bucket.central_logs.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AWSCloudTrailAclCheck"
        Effect    = "Allow"
        Principal = { Service = "cloudtrail.amazonaws.com" }
        Action    = "s3:GetBucketAcl"
        Resource  = aws_s3_bucket.central_logs.arn
      },
      {
        Sid       = "AWSCloudTrailWrite"
        Effect    = "Allow"
        Principal = { Service = "cloudtrail.amazonaws.com" }
        Action    = "s3:PutObject"
        Resource  = "${aws_s3_bucket.central_logs.arn}/cloudtrail/*"
        Condition = {
          StringEquals = {
            "s3:x-amz-acl" = "bucket-owner-full-control"
          }
        }
      },
      {
        Sid       = "AWSConfigAclCheck"
        Effect    = "Allow"
        Principal = { Service = "config.amazonaws.com" }
        Action    = "s3:GetBucketAcl"
        Resource  = aws_s3_bucket.central_logs.arn
      },
      {
        Sid       = "AWSConfigWrite"
        Effect    = "Allow"
        Principal = { Service = "config.amazonaws.com" }
        Action    = "s3:PutObject"
        Resource  = "${aws_s3_bucket.central_logs.arn}/config/*"
        Condition = {
          StringEquals = {
            "s3:x-amz-acl" = "bucket-owner-full-control"
          }
        }
      },
      {
        Sid       = "AllowSSLRequestsOnly"
        Effect    = "Deny"
        Principal = "*"
        Action    = "s3:*"
        Resource  = [aws_s3_bucket.central_logs.arn, "${aws_s3_bucket.central_logs.arn}/*"]
        Condition = {
          Bool = { "aws:SecureTransport" = "false" }
        }
      },
    ]
  })
}

# ---------------------------------------------------------------------------
# Event notifications (CKV2_AWS_62). Tamper detection: if anything ever
# deletes or restores from the archive, push the event onto an SNS topic so
# the SOC pipeline can pick it up. ObjectCreated would be too noisy (every
# CloudTrail/Config write fires); ObjectRemoved + LifecycleTransition + the
# replication failure events are what indicate an integrity issue.
# ---------------------------------------------------------------------------
resource "aws_sns_topic" "central_logs_events" {
  provider          = aws.log_archive
  name              = "${local.central_logs_bucket_prefix}-events"
  kms_master_key_id = aws_kms_key.central_logs.id
  tags              = local.default_tags
}

data "aws_iam_policy_document" "central_logs_events" {
  provider = aws.log_archive
  statement {
    sid    = "AllowS3Publish"
    effect = "Allow"
    actions = ["SNS:Publish"]
    principals {
      type        = "Service"
      identifiers = ["s3.amazonaws.com"]
    }
    resources = [aws_sns_topic.central_logs_events.arn]
    condition {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
      values   = [aws_s3_bucket.central_logs.arn]
    }
  }
}

resource "aws_sns_topic_policy" "central_logs_events" {
  provider = aws.log_archive
  arn      = aws_sns_topic.central_logs_events.arn
  policy   = data.aws_iam_policy_document.central_logs_events.json
}

resource "aws_s3_bucket_notification" "central_logs" {
  provider = aws.log_archive
  bucket   = aws_s3_bucket.central_logs.id

  topic {
    topic_arn = aws_sns_topic.central_logs_events.arn
    events = [
      "s3:ObjectRemoved:*",
      "s3:LifecycleExpiration:*",
      "s3:Replication:OperationFailedReplication",
      "s3:Replication:OperationMissedThreshold",
    ]
  }

  depends_on = [aws_sns_topic_policy.central_logs_events]
}

# ---------------------------------------------------------------------------
# DR replica bucket + cross-region replication (CKV_AWS_144 / FedRAMP CP-9).
# Source is the primary central-logs bucket; destination is a same-name bucket
# in eu-west-3 created under the LogArchive account's DR
# provider. The replica KMS key (kms.tf) lets the replicated SSE-KMS objects
# be decrypted in the DR region.
# ---------------------------------------------------------------------------
resource "aws_s3_bucket" "central_logs_dr" {
  # checkov:skip=CKV_AWS_18: DR replica inherits the primary's circular-logging rationale; same SoC visibility via CloudTrail data events + replica SNS notifications
  provider = aws.log_archive_eu_west_3
  bucket   = "${local.central_logs_bucket_prefix}-dr-${random_id.bucket_suffix.hex}"

  force_destroy = false
  object_lock_enabled = true

  tags = merge(local.default_tags, {
    Name    = "central-logs-dr"
    Purpose = "DR replica of central log archive in eu-west-3"
  })
}

resource "aws_s3_bucket_versioning" "central_logs_dr" {
  provider = aws.log_archive_eu_west_3
  bucket   = aws_s3_bucket.central_logs_dr.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "central_logs_dr" {
  provider = aws.log_archive_eu_west_3
  bucket   = aws_s3_bucket.central_logs_dr.id

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_replica_key.central_logs_eu_west_3.arn
      sse_algorithm     = "aws:kms"
    }
    bucket_key_enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "central_logs_dr" {
  provider                = aws.log_archive_eu_west_3
  bucket                  = aws_s3_bucket.central_logs_dr.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Lifecycle on the DR bucket — same retention floor as the primary (CKV2_AWS_61).
# Failed-multipart-upload cleanup is in a dedicated unfiltered rule (CKV_AWS_300)
# so it applies bucket-wide independent of the expire-old-logs filter.
resource "aws_s3_bucket_lifecycle_configuration" "central_logs_dr" {
  provider = aws.log_archive_eu_west_3
  bucket   = aws_s3_bucket.central_logs_dr.id

  rule {
    id     = "abort-incomplete-multipart-uploads"
    status = "Enabled"
    filter {}
    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  rule {
    id     = "expire-old-logs"
    status = "Enabled"
    filter {
      prefix = ""
    }
    noncurrent_version_expiration {
      noncurrent_days = 90
    }
    expiration {
      days = 3650
    }
    transition {
      days          = 30
      storage_class = "STANDARD_IA"
    }
    transition {
      days          = 90
      storage_class = "GLACIER"
    }
  }
}

# DR bucket event notifications (CKV2_AWS_62) — tamper detection in the DR
# region. Routes ObjectRemoved + Lifecycle + replication-arriving events to a
# DR-local SNS topic so the SoC pipeline gets a copy in eu-west-3
# even if the primary region is in failover.
resource "aws_sns_topic" "central_logs_events_dr" {
  provider          = aws.log_archive_eu_west_3
  name              = "${local.central_logs_bucket_prefix}-events-dr"
  kms_master_key_id = aws_kms_replica_key.central_logs_eu_west_3.id
  tags              = local.default_tags
}

data "aws_iam_policy_document" "central_logs_events_dr" {
  provider = aws.log_archive_eu_west_3
  statement {
    sid    = "AllowS3Publish"
    effect = "Allow"
    actions = ["SNS:Publish"]
    principals {
      type        = "Service"
      identifiers = ["s3.amazonaws.com"]
    }
    resources = [aws_sns_topic.central_logs_events_dr.arn]
    condition {
      test     = "ArnEquals"
      variable = "aws:SourceArn"
      values   = [aws_s3_bucket.central_logs_dr.arn]
    }
  }
}

resource "aws_sns_topic_policy" "central_logs_events_dr" {
  provider = aws.log_archive_eu_west_3
  arn      = aws_sns_topic.central_logs_events_dr.arn
  policy   = data.aws_iam_policy_document.central_logs_events_dr.json
}

resource "aws_s3_bucket_notification" "central_logs_dr" {
  provider = aws.log_archive_eu_west_3
  bucket   = aws_s3_bucket.central_logs_dr.id

  topic {
    topic_arn = aws_sns_topic.central_logs_events_dr.arn
    events = [
      "s3:ObjectRemoved:*",
      "s3:LifecycleExpiration:*",
      "s3:ReducedRedundancyLostObject",
    ]
  }

  depends_on = [aws_sns_topic_policy.central_logs_events_dr]
}

# IAM role S3 replication uses to read from the source and write to the
# destination — both KMS-encrypted, so the role needs Decrypt on the primary
# CMK and Encrypt on the replica CMK.
data "aws_iam_policy_document" "central_logs_replication_assume" {
  provider = aws.log_archive
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["s3.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "central_logs_replication" {
  provider           = aws.log_archive
  name               = "${local.central_logs_bucket_prefix}-replication"
  assume_role_policy = data.aws_iam_policy_document.central_logs_replication_assume.json
  tags               = local.default_tags
}

data "aws_iam_policy_document" "central_logs_replication" {
  provider = aws.log_archive
  statement {
    actions = [
      "s3:GetReplicationConfiguration",
      "s3:ListBucket",
      "s3:GetObjectVersionForReplication",
      "s3:GetObjectVersionAcl",
      "s3:GetObjectVersionTagging",
    ]
    resources = [
      aws_s3_bucket.central_logs.arn,
      "${aws_s3_bucket.central_logs.arn}/*",
    ]
  }
  statement {
    actions = [
      "s3:ReplicateObject",
      "s3:ReplicateDelete",
      "s3:ReplicateTags",
    ]
    resources = ["${aws_s3_bucket.central_logs_dr.arn}/*"]
  }
  statement {
    actions   = ["kms:Decrypt"]
    resources = [aws_kms_key.central_logs.arn]
  }
  statement {
    actions   = ["kms:Encrypt", "kms:GenerateDataKey"]
    resources = [aws_kms_replica_key.central_logs_eu_west_3.arn]
  }
}

resource "aws_iam_role_policy" "central_logs_replication" {
  provider = aws.log_archive
  name     = "${local.central_logs_bucket_prefix}-replication"
  role     = aws_iam_role.central_logs_replication.id
  policy   = data.aws_iam_policy_document.central_logs_replication.json
}

resource "aws_s3_bucket_replication_configuration" "central_logs" {
  provider = aws.log_archive
  role     = aws_iam_role.central_logs_replication.arn
  bucket   = aws_s3_bucket.central_logs.id

  rule {
    id     = "replicate-all"
    status = "Enabled"

    filter {}

    delete_marker_replication {
      status = "Enabled"
    }

    source_selection_criteria {
      sse_kms_encrypted_objects {
        status = "Enabled"
      }
    }

    destination {
      bucket        = aws_s3_bucket.central_logs_dr.arn
      storage_class = "STANDARD_IA"
      encryption_configuration {
        replica_kms_key_id = aws_kms_replica_key.central_logs_eu_west_3.arn
      }
    }
  }

  # Source bucket versioning must exist before replication can attach.
  depends_on = [
    aws_s3_bucket_versioning.central_logs,
    aws_s3_bucket_versioning.central_logs_dr,
  ]
}
